# Generated by Django 4.1.6 on 2023-03-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSchool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='Materias',
            new_name='Materia',
        ),
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
