# Generated by Django 4.1.6 on 2023-03-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSchool', '0003_alter_nota_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='dni',
            new_name='legajo',
        ),
    ]
